spring.application.name=springsecurity
server.servlet.context-path=/api/v1

spring.datasource.url=jdbc:postgresql://localhost:5431/postgres
spring.datasource.username=postgres
spring.datasource.password=password

jwt.secretKey=baufbaiwefaweufeaiufavisbvsdipisdnvaskjvskvpofpowaejrfposdkvnalsdvbafjbkujfewoifjwaajsbdifuauifbvdoivnoiehgoihervbikfbaiub

# 1. Let Hibernate create/update the table structure automatically
spring.jpa.hibernate.ddl-auto=update

# 2. Ensure data.sql runs every time the app starts
spring.sql.init.mode=always

# 3. CRITICAL: Wait for Hibernate to create the table BEFORE running data.sql
spring.jpa.defer-datasource-initialization=true

#spring.security.user.name=dhananjay
#spring.security.user.password=password